language: c

script:
  - ./autogen.sh
  - ./configure && make
  - sudo make install

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y intltool libxml2-dev libxslt1-dev libgtk-3-dev libwebkitgtk-3.0-dev libpeas-dev libsqlite3-dev libjson-glib-dev libgirepository1.0-dev gsettings-desktop-schemas-dev
